### PR TITLE
3.0.0 release

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Do not merge this if you are not aware of the context. Also, I'd like @thiemowmde to double check all is fluff before making the actual release.

**Comment by thiemowmde** [comment]
* I would like to do some more breaking changes in 3.0.0 (basically all but fingerprint), possibly #425 and #467.
* Some tests are still missing but unmerged, especially #423 and #441.
* #466 blocks this.

**Comment by JeroenDeDauw** [comment]
I do not think we need to wait on the outcome of #466 to make this release, since the change it proposes is the narrowing of a methods return contract, with is not a breaking change. We can easily merge this after the 3.0 release and have it in 3.1.

**Comment by thiemowmde** [comment]
Now also blocked by https://phabricator.wikimedia.org/T98180.

**Comment by JeroenDeDauw** [comment]
I think it is unwise to block serious refactoing on goldplating. The enemy of the good is the perfect. As long as this release has not happened, the amount of code that constructs Statements by doing `new Statement( new Claim(  ... ) )` will increase. The same goes for various other things, such as replacing `Claims` with new things in this release.

**Comment by thiemowmde** [comment]
I'm blocking this because what's currently in master is not the result of decisions made in a team any more.

**Comment by Benestar** [comment]
Per discussion with PM this is on hold until it is correctly tracked in a sprint on phabricator.

**Comment by JeroenDeDauw** [comment]
If I'm not mistaken we tackled everything people where intent on getting done before 3.0. So can we move on now?

**Comment by JeroenDeDauw** [comment]
To my knowledge all blockers have been tackled now

**Comment by Benestar** [comment]
I also see no more blockers on this release. Would be great if we could manage to release this compontent in the next sprint.

**Pull request merged**
