### PR TITLE
Introduce constants for StatementGrouper names

### PR DESCRIPTION
**Pull request by thiemowmde**
This goes along with:
* https://github.com/wmde/WikibaseDataModelServices/pull/97
* https://gerrit.wikimedia.org/r/258124
* https://gerrit.wikimedia.org/r/257880

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Needs a since tag and rel notes update

**Comment by thiemowmde** [comment]
Will update release notes in a commit shortly before the release.

**Comment by JeroenDeDauw** [comment]
+0 from my side

**Comment by Benestar** [comment]
Not sure this is needed. I wonder what the use case is for this constant.

**Comment by thiemowmde** [comment]
Use case can be seen in https://gerrit.wikimedia.org/r/257880.

**Comment by thiemowmde** [comment]
@Jonas-WMDE, do you receive this comment?

**Pull request merged**
