### PR TITLE
Add floobits config

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by thiemowmde** [comment]
Why does this need to be in master?

**Comment by JeroenDeDauw** [comment]
Do you think it should be on another branch?

**Comment by thiemowmde** [comment]
Probably. How is this needed by other people outside of the office?

**Comment by JeroenDeDauw** [comment]
It is useful for people that want to open the project with Floobits

**Comment by thiemowmde** [comment]
This doesn't really answer the question why this needs to be in master to open the project with <whatever service people want to use>.

**Comment by JeroenDeDauw** [comment]
It does not need to be there. However, if it is not, it is created, which is then annoying git wise.

**Comment by thiemowmde** [comment]
Self-merge? O_o Question why this needs to be in master is still unanswered.

**Pull request merged**
