### PR TITLE
Allow installation on PHP 8.0 systems

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Right now people on PHP 8.x get data-model 9.2, which is not helping anyone. The tests all pass on PHP 8.0.

**Comment by JeroenDeDauw** [comment]
@addshore @manicki

**Comment by JeroenDeDauw** [comment]
Why does this take 20 days?

**Comment by mariushoch** [comment]
Manually ran the tests in a PHP 8.0.0 container and this seems to work fine.

**Comment by manicki** [comment]
> Why does this take 20 days?

Apologies, this fell off our radar apparently.

**Pull request merged**
