### PR TITLE
Use With instead of By for consistency in this class

### PR DESCRIPTION
**Pull request by Benestar**

### CODE REVIEW

**Comment by thiemowmde** [comment]
-2. What consistency?

**Comment by Benestar** [comment]
consistency **in this class** &ndash; please read the commit message

**Comment by Benestar** [comment]
**By**Guid suggests that all statements will be returned grouped **by** their GUID. However, this method returns only one statement **with** the specified GUID. It's English grammar, it has to be `With`.

**Comment by JeroenDeDauw** [comment]
The naming of `StatementByGuidMap` is a different topic. I don't think anyone is saying that `StatementWithGuidMap` would be a sane name.

**Comment by JeroenDeDauw** [comment]
I'll update the readme

**Comment by thiemowmde** [comment]
Still -1. I did not picked the method name by a dice roll or something. I picked it **for consistency** with `StatementByGuidMap`. Please fix both or nothing.

**Comment by thiemowmde** [comment]
@JeroenDeDauw Why the merge? My -1 above was pretty specific. This is not how decisions in a team should be made. What now? Should I submit an other revert patch?

**Comment by Benestar** [comment]
@thiemowmde There is an obvious difference between both use cases. The `StatementByGuidMap` does **grouping by** guid while the method returns a single statement **with** guid.

Using by for grouping and with for selecting is just the correct use of English prepositions.

**Comment by JeroenDeDauw** [comment]
@thiemowmde you told me in person that it really does not matter all that much. Promoting such a thing to whole team discussion is as bikeshed as you can go. We have more important things to direct our attention at

**Comment by thiemowmde** [comment]
Tracked in https://phabricator.wikimedia.org/T98180.

**Comment by thiemowmde** [comment]
> you told me in person that it really does not matter

I found this patch, questioned our naming decision (you introduced it in #414, I reviewed it, I sticked with it in #450, you merged it) as ridiculous as you did and expected you to ignore it.

> removed your -2

And left a -1.

> promoting such a thing to whole team discussion is as bikeshed as you can go.

What I'm promoting as a discussion is how decisions are made in a team.

**Pull request merged**
