### PR TITLE
Add FingerprintHolder interface

### PR DESCRIPTION
**Pull request by Benestar**
This interface is the same as `StatementListHolder` for `StatementListProvider`. We might also consider to add the setter to `FingerprintProvider` itself but I guess the same argumentation as for `StatementListHolder` will happen and we should stay consistent here.

### CODE REVIEW

**Comment by Benestar** [comment]
We should also discuss if this pattern should be applied for all interfaces introduced in #513

**Comment by JeroenDeDauw** [comment]
Still not entirely convinced this approach is good. +1

**Comment by addshore** [comment]
needs rebase

**Comment by Benestar** [comment]
@addshore rebased ;-)

**Pull request merged**
