### PR TITLE
[WIP] Rewrite ByPropertyIdArray

### PR DESCRIPTION
**Pull request by Benestar**
This should replace `ByPropertyIdArray`. Just a draft for now, needs lots of testing to make sure it actually replicates the behaviour of the old version of the class. However, I'm already quite proud of using only half as much codes as the old implementation.

### CODE REVIEW

**Comment by Benestar** [comment]
@JeroenDeDauw @thiemowmde is it worth to work on this PR again or are there already alternatives to `ByPropertyIdArray`?

**Comment by JeroenDeDauw** [comment]
There is the `ByPropertyIdGrouper` that you created... no further work has been done in this direction IIRC

**Comment by thiemowmde** [comment]
I find this class scary, before and after the rewrite. I will not spend time on this.

**Comment by Benestar** [comment]
New approach made in #479

**Pull request closed without merging**
