### PR TITLE
Release 6.2.0

### PR DESCRIPTION
**Pull request by jakobw**

### CODE REVIEW

**Comment by manicki** [comment]
Please wait for https://github.com/wmde/WikibaseDataModel/pull/685 with releasing (whoever does it)!

**Comment by manicki** [comment]
I am wondering shouldn't this also mention in some way that EntityId's constructor has become public again. You don't create instances of abstract classes but the public interface has changed, still.

**Comment by thiemowmde** [comment]
If the constructor parameters changed and a third-party subclass calling `parent::__construct` must be changed because of this, then yes, this is relevant and should be mentioned.

**Comment by manicki** [comment]
I believe this is what happened in https://github.com/wmde/WikibaseDataModel/pull/678/files so I guess this change should be listed too.

**Comment by jakobw** [comment]
Thanks, @manicki. Added a line mentioning the now public constructor.

**Pull request merged**
