### PR TITLE
Merge master into 3.0.x-dev

### PR DESCRIPTION
**Pull request by thiemowmde**
I checked and can not spot any conflict. Please double-check.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Cannot be merged due to conflict

**Comment by thiemowmde** [comment]
How to solve? This is no branch I can checkout and fix.

**Comment by JeroenDeDauw** [comment]
Create a branch based from master or 3.0.x and merge the other thing into it. Then push that branch and make a pull req of the thing into 3.0.x

**Comment by thiemowmde** [comment]
Re-submitted as #406.

**Pull request closed without merging**
