### PR TITLE
Add isEmpty to EntityDocument

### PR DESCRIPTION
**Pull request by Benestar**
This is part of the RFC on phabricator: https://phabricator.wikimedia.org/T110177

### CODE REVIEW

**Comment by thiemowmde** [comment]
I can not think of a reason why an entity type should *not* have an isEmpty method. Basically: Can you think of an entity type where it's not possible to tell if it's empty or not? In a worst case scenario it can simply return true all the time. So +2 from my side, but I want to wait for opinions of other team members.

**Comment by JeroenDeDauw** [comment]
Y u create new issue? ;p There already was one https://phabricator.wikimedia.org/T109581

**Comment by Benestar** [comment]
@JeroenDeDauw that is only about isEmpty and not about the other methods. Should've linked it though.

**Comment by JeroenDeDauw** [comment]
@Benestar so is this PR right? ;p

**Comment by JeroenDeDauw** [comment]
Strictly speaking this is a breaking change. However, this is one of those cases where it might be more pragmatic to deviate a bit.

**Comment by Benestar** [comment]
I think via the comments here and on [phabricator](https://phabricator.wikimedia.org/T110177) this can be merged safely.

**Comment by JeroenDeDauw** [comment]
As this is a breaking change for derivatives of EntityDocument, can someone check nothing will blow up when putting this in a minor release? I think we might have test doubles in some other component that implement the interface.

**Comment by Benestar** [comment]
I also don't object if we wait until other changes and do a 5.0. This really isn't an urgent request.

**Comment by JeroenDeDauw** [comment]
If nothing in our codebase will actually break, I think for this case it's fine to release as 4.x. Even if something breaks, and we'll be able to deal with it quickly. Can someone check? I'm not able to ATM

**Comment by JeroenDeDauw** [comment]
@brightbyte did you do the verification?

**Comment by thiemowmde** [comment]
Subclasss of EntityDocument in my local code base:
* Entity, Item and Property.
* [Wikibase\DataModel\Fixtures\EntityOfUnknownType](https://github.com/wmde/WikibaseDataModel/blob/master/tests/fixtures/EntityOfUnknownType.php)
* [Wikibase\DataModel\Services\Fixtures\EntityOfUnknownType](https://github.com/wmde/WikibaseDataModelServices/blob/master/tests/fixtures/EntityOfUnknownType.php)
* [Wikibase\DataModel\Services\Fixtures\FakeEntityDocument](https://github.com/wmde/WikibaseDataModelServices/blob/master/tests/fixtures/FakeEntityDocument.php)

**Comment by JeroenDeDauw** [comment]
Thanks @thiemowmde.

That means DMS's tests will blow up when we tag this. Actually, they already did as we where testing with a dev version of DM as well. @Benestar fixed this with https://github.com/wmde/WikibaseDataModelServices/commit/66df0d70eac52bca51272ec96964f643af38227b, though that is ignoring the issue rather than addressing it properly. Based on that I suggest we tag ASAP and fix the DMS tests.

**Pull request merged**
