### PR TITLE
Remove SnakRole

### PR DESCRIPTION
**Pull request by thiemowmde**
I have never seen this before. Not used anywhere in my code base, including the major extensions we use. I have not checked for other external usages yet.

### CODE REVIEW

**Comment by Benestar** [comment]
+1 for the next major release

**Comment by JeroenDeDauw** [comment]
Used in Wikibase QueryEngine

**Comment by Benestar** [comment]
Wikibase QueryEngine has been abandoned and thus not relevant here anymore.

**Comment by JeroenDeDauw** [comment]
I have a fork that is not abandoned. Besides, relevance can come in the form of demonstrating something has a certain use, even if that something is not used in that manner at present.

**Pull request closed without merging**
