### PR TITLE
Remove deprecated Claims class

### LINKED ISSUE #157: Deprecate and remove Claims class
The Claims class currently has the highest complexity of this component.

worst

DataModel 1.0 introduces `ClaimList`, which is a partial alternative. `Entity` and `Item` type hint against this type in several methods.

### PR DESCRIPTION
**Pull request by Benestar**
Fixes #157 
See https://phabricator.wikimedia.org/T78281
See https://gerrit.wikimedia.org/r/#/c/235684/

### CODE REVIEW

**Comment by thiemowmde** [comment]
Please split this patch into two: One that removes all remaining usages of this class, the second removes the class.

**Comment by JeroenDeDauw** [comment]
No need to split if we're fine with none of this being merged before we switch master to 5.x-dev. Given there is only a single small change in a test method that gets delayed like this, I suspect that is the case.

**Comment by thiemowmde** [comment]
Rebased. Please note that this is the same as/part of #557.

**Comment by thiemowmde** [comment]
I did a rebase with no other change. @Benestar, feel free to merge this. +2 from my side.

**Comment by JeroenDeDauw** [comment]
Finally fully rid of this class \o/

**Pull request merged**
