### PR TITLE
Switched arrays over to short array syntax

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Includes the necessary bump of the required PHP version

### CODE REVIEW

**Comment by thiemowmde** [comment]
Doesn't this need a 7.0.0 version bump because it's a breaking change?

**Comment by JeroenDeDauw** [comment]
Nope http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by mariushoch** [comment]
+1, diff looks good at a glance.

**Comment by brightbyte** [comment]
needs rebase. any takers?

**Comment by JeroenDeDauw** [comment]
Run script again, much easier than rebase. And don't do this while other work is going on in the component...

**Pull request closed without merging**
