### PR TITLE
Revert "Make ReferenceList no longer extend SplObjectStorage "

### PR DESCRIPTION
**Pull request by Benestar**
Reverts wmde/WikibaseDataModel#500

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
wtf? Why the revert, and why the self merge?

**Comment by JeroenDeDauw** [comment]
Note: this is not a merge into master (I was wtf for a bit until realizing)

**Comment by Benestar** [comment]
I tried to resolve the conflicts that occured after the original patch got merged but finally decided to rework all of the patches and resubmit them. Github weirdness -.-

**Comment by JeroenDeDauw** [comment]
Benestar weirdness!

**Pull request merged**
