### PR TITLE
Allow iterable in SiteLinkList constructor

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Like we just did with TermList

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Such review?

**Comment by thiemowmde** [comment]
You could link this to a Phabricator ticket and make sure it's in the review column of a board one of the relevant teams is actively working on.

**Comment by JeroenDeDauw** [comment]
At present it is completely unclear to me who is responsible for what Wikidata related code. Also not clear to me I can jut put something in the review column of a team.

**Comment by manicki** [comment]
apologies for late response

> Do you mean that it is preferred for the team to do such things themselves 

I meant this ^

**Pull request merged**
