### PR TITLE
Rename Fingerprint to EntityTerms

### PR DESCRIPTION
**Pull request by thiemowmde**
This does __not__ make #301 (now https://phabricator.wikimedia.org/T78286) obsolete, but is a first step.

https://phabricator.wikimedia.org/T87237

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
This rename causes a pile of work - we need to update a lot of code using the class and the methods in most of the PHP components that depend on DataModel. Plus rename things such as fingerprint view, causing further breaking changes, including in our JS components. No reasoning has been provided for why this rename should happen, and I certainly don't see anything that justifies the cost. so -2 from my side.

**Comment by thiemowmde** [comment]
> including in our JS components.

Already renamed.

> No reasoning has been provided for why this rename should happen

This is just not true. We talked about this a gazillion times.

**Comment by addshore** [comment]
As the class itself isn't changing structure could we leave a class alias and also keep getFingerprint for at least one release? Thus not immediately breaking everything that uses these bits of code ?

**Comment by thiemowmde** [comment]
Since this is the first time (I'm aware of) we working on a branch, why is this not mergeable any more and how do I rebase this?

**Comment by thiemowmde** [comment]
Erm, why? We did not agreed on a way forward, this is still a possibility. Reopen please.

**Comment by JeroenDeDauw** [comment]
GitHub automatically closed this when I removed the 3.0.x-dev branch. Needs a new PR against master.

**Pull request closed without merging**
