### PR TITLE
Add EntityRedirect & Test

### PR DESCRIPTION
**Pull request by addshore**
This is a copy and paste from Wikibase Lib

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
> Trying to @cover or @use not existing class or interface "Wikibase\Lib\Store\EntityRedirect"

**Comment by JeroenDeDauw** [comment]
Submitted #535 to find such issues earlier

**Comment by thiemowmde** [comment]
Let's move this to DataModel please. This is not even a "service".

**Comment by addshore** [comment]
This is in DataModel ;)

**Pull request merged**
