### PR TITLE
More specific exception messages in DispatchingEntityIdParser

### PR DESCRIPTION
**Pull request by thiemowmde**
This patch does not change semantics, but:
* Inline trivial methods.
* Re-throw the original message if one of the builders fails, which should not happen because all they (currently) do is checking against the same regex.
* Reword the final message.

This is split from #346 to make it much more focused.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I don't agree with this inlining.

Is there an actual problem being solved here? My guess is that this supposedly improves performance, though I'm kinda dubious about this change having much of an impact in that field.

**Comment by thiemowmde** [comment]
Yes, there are two actual problems:

1. Readability. This could be a really, really simple implementation, but instead you have to jump back and forth between all these super-trivial methods to finally understand what's happening. I find such an excessive splitting not helpful.
2. It's impossible to have separate messages for the three cases "parsing failed", "no matching parser found" and "no parser configured at all".

**Comment by JeroenDeDauw** [comment]
I disagree this makes readability better

**Comment by thiemowmde** [comment]
So you agree with 2. then? Fine. Can we move on?

**Comment by thiemowmde** [comment]
After rebasing this is now identical to #346.

**Pull request closed without merging**
