### PR TITLE
Remove unused methods

### PR DESCRIPTION
**Pull request by Benestar**
Methods which were never used in our code base or have an easy replacement got removed

### CODE REVIEW

**Comment by thiemowmde** [comment]
I don't think you can remove the serialize methods. They are used when calling PHP's `serialize()` function.

**Comment by Benestar** [comment]
We never implemented the `Serializable` interface actually so I think these methods weren't of much use. Furthermore, in the next patches, this class will no longer extend `SplObjectStorage` anyways so one can just serialize the array variable.

**Comment by thiemowmde** [comment]
I was curious and checked and yes, PHP only calls the methods if the class does implement the `Serializable` interface.

**Comment by Benestar** [comment]
Resubmitted against the correct branch #501

**Pull request closed without merging**
