### PR TITLE
Throw exception rather than ignoring non-iterable

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Just ran into this while working on new term store stuff

### CODE REVIEW

**Comment by thiemowmde** [comment]
The strict type hints that prevented this from happening before have been removed with #788, #789, and #791, with no replacement other than a `/* iterable */` comment. Notably all these patches have been self-merged by @JeroenDeDauw. @manicki or @RazShutyWMDE, may I ask if this is accepted standard procedure in the team?

**Comment by manicki** [comment]
> Notably all these patches have been self-merged by @JeroenDeDauw. @manicki or @RazShutyWMDE, may I ask if this is accepted standard procedure in the team?

All three pull requests you've linked to have gone through review, and have been accepted by a reviewer. Merging happened after approval, which is absolutely in line with the code review process we follow.
It is true though, that the process has not been 100% followed in the case of https://github.com/wmde/WikibaseDataModel/pull/788, i.e. none of reviewers have clicked "accept" button. But reading through comments on the said pull requests shows there was no objection to have code change merged. This particular case was not optimal indeed, and we will try better next time.

**Comment by JeroenDeDauw** [comment]
Rebased - ci passes now

**Comment by JeroenDeDauw** [comment]
> This particular case was not optimal indeed, and we will try better next time.

Not that a single developer running into a minor inconvenience after several months is a big issue. We did well enough

**Comment by JeroenDeDauw** [comment]
@manicki don't forget to hit the big green button

red-is-the-new-green

**Comment by manicki** [comment]
thanks for the reminder, I thought I had done that after the HHVM CI failures have been fixed for this repo.

**Pull request merged**
