### PR TITLE
Revert "Add floobits config"

### PR DESCRIPTION
**Pull request by thiemowmde**
Reverts wmde/WikibaseDataModel#418

### CODE REVIEW

**Comment by thiemowmde** [comment]
Why are we adding meta data from random tools to a code base? We are not adding PHPStorm's `.idea`, for example. Why should we add this?

**Comment by JeroenDeDauw** [comment]
This tool is just as random as ScrutinizerCI, for which we also have such config. What is the problem with this being in the repo?

**Comment by Benestar** [comment]
I agree with Thiemo that we should reduce the number of config files included into the repository to a minimum. ScrutinizerCI is included as it is part of our deployment and testing system but as far as I understand floobit is not used by all developers of this library.

**Comment by thiemowmde** [comment]
@JeroenDeDauw, you realize that "does not hurt" is not an answer to the question who needs this, why and why it needs to be in the master branch in one of our central repositories? There are already a lot of such config files in our repositories (by the way, what's `.coveralls.yml`?) and each raises the same questions: What does it mean, why is it there, must it be considered when changing something in the repository, is it still needed or an outdated fragment? You are often talking about "maintenance costs". I don't see how this is an exception that doesn't need discussion.

**Comment by thiemowmde** [comment]
#418 was a self-merge, so ...

**Comment by Benestar** [comment]
Sorry, I wanted this to merge as well, forgot about it. So no self-merge but approved by me ;-)

**Pull request merged**
